
    create table data_source_hash (
        updated_at timestamp(6) with time zone not null,
        id uuid not null,
        source_key varchar(120) not null unique,
        hash varchar(128) not null,
        primary key (id)
    );

    create table flip (
        snapshot_timestamp_epoch_millis bigint,
        id uuid not null,
        flip_type varchar(255) check ((flip_type in ('AUCTION','BAZAAR','CRAFTING','FORGE','KATGRADE','FUSION'))),
        result_item_id varchar(255) not null,
        primary key (id)
    );

    create table flip_constraints (
        int_value integer,
        long_value bigint,
        flip_id uuid not null,
        constraint_type varchar(255) not null check ((constraint_type in ('MIN_FORGE_SLOTS','RECIPE_UNLOCKED','MIN_CAPITAL'))),
        string_value varchar(255)
    );

    create table flip_step (
        duration_factor float(53),
        resource_units integer not null,
        step_order integer,
        base_duration_seconds bigint,
        flip_id uuid not null,
        id uuid not null,
        duration_type varchar(255) not null check ((duration_type in ('FIXED','MARKET_BASED','INSTANT'))),
        params_json text,
        resource varchar(255) not null check ((resource in ('NONE','FORGE_SLOT'))),
        scheduling_policy varchar(255) not null check ((scheduling_policy in ('NONE','BEST_EFFORT','LIMITED_BY_RESOURCE'))),
        type varchar(255) not null check ((type in ('BUY','SELL','CRAFT','FORGE','FUSION','WAIT'))),
        primary key (id)
    );

    create table item_info_links (
        position integer not null,
        info_link varchar(255) not null,
        item_id varchar(255) not null,
        primary key (position, item_id)
    );

    create table items (
        category varchar(255),
        display_name varchar(255),
        item_id varchar(255) not null,
        minecraft_id varchar(255),
        rarity varchar(255),
        lore oid,
        primary key (item_id)
    );

    create table market_snapshot (
        auction_count integer not null,
        bazaar_product_count integer not null,
        created_at_epoch_millis bigint not null,
        snapshot_timestamp_epoch_millis bigint not null,
        id uuid not null,
        auctions_json text not null,
        bazaar_products_json text not null,
        primary key (id)
    );

    create table recipe_ingredients (
        amount integer not null,
        id bigint generated by default as identity,
        item_internal_name varchar(255) not null,
        recipe_id varchar(255) not null,
        primary key (id)
    );

    create table recipes (
        process_duration_seconds bigint not null,
        output_item_id varchar(255) not null,
        process_type varchar(255) not null check ((process_type in ('CRAFT','FORGE','KATGRADE'))),
        recipe_id varchar(255) not null,
        primary key (recipe_id)
    );

    create index idx_flip_snapshot_ts_epoch_millis
       on flip (snapshot_timestamp_epoch_millis);

    create index idx_market_snapshot_snapshot_ts_epoch_millis
       on market_snapshot (snapshot_timestamp_epoch_millis);

    alter table if exists flip_constraints
       add constraint FKmwsv7e5kia37jc5o8viqe69s2
       foreign key (flip_id)
       references flip;

    alter table if exists flip_step
       add constraint FKsdkp89mkhwmrhkay6wm24ociv
       foreign key (flip_id)
       references flip;

    alter table if exists item_info_links
       add constraint FK1qvvsf50dwlcdvlpobn19jjgx
       foreign key (item_id)
       references items;

    alter table if exists recipe_ingredients
       add constraint FKcqlw8sor5ut10xsuj3jnttkc
       foreign key (recipe_id)
       references recipes;

    alter table if exists recipes
       add constraint FK98aujkehipafs7ko4rb050vfq
       foreign key (output_item_id)
       references items;